# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
ar1= np.random.random((3,3,3))
print(ar1)

[[[0.22792281 0.41784534 0.30254263]
  [0.30436407 0.78202463 0.11808413]
  [0.68297713 0.60312326 0.00360184]]

 [[0.45812353 0.05002107 0.50185672]
  [0.39952953 0.62821908 0.28938793]
  [0.51778304 0.96338941 0.11219254]]

 [[0.01338611 0.18934609 0.24012581]
  [0.94217122 0.70297558 0.60096041]
  [0.98532744 0.92726612 0.3450726 ]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
ar2= np.diag([0,1,2,3,4])
print(ar2)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
ar3 = np.ones((3,3))
print("Checkerboard pattern:")
ar3 = np.zeros((8,8),dtype=int)
ar3[1::2,::2] = 1
ar3[::2,1::2] = 1
print(ar3)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [9]:
ar4= np.random.random((3,3))
print("Original Array:")
print(ar4)
xmax, xmin = ar4.max(), ar4.min()
ar4 = (ar4 - xmin)/(xmax - xmin)
print("After normalization:")
print(ar4)


Original Array:
[[0.03153351 0.03595841 0.02736807]
 [0.33538457 0.6691112  0.61279381]
 [0.76593433 0.75191326 0.13553417]]
After normalization:
[[0.0056399  0.0116311  0.        ]
 [0.41704654 0.86890394 0.79265162]
 [1.         0.98101582 0.14645416]]


# 5.  How to find common values between two arrays?

In [10]:
a1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",a1)
a2 = [10, 30, 40]
print("Array2: ",a2)
print("Common values between two arrays:")
print(np.intersect1d(a1, a2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [11]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [12]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 0 1 1 1]
Second array:
[0 1 1 1 1 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [13]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.19249441 0.22606943 0.88848574 0.62999153 0.71148512 0.33004517
 0.35029678 0.62008454 0.47395644 0.6501781 ]
Maximum value replaced by 0:
[0.19249441 0.22606943 0.         0.62999153 0.71148512 0.33004517
 0.35029678 0.62008454 0.47395644 0.6501781 ]


# 9. How to print all the values of an array?

In [17]:
np.set_printoptions(threshold=np.inf)
x = np.ones((4, 4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 10.Subtract the mean of each row of a matrix

In [18]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.63316708 0.85056349 0.15695281 0.90655409 0.43193322 0.33981367
  0.32013814 0.32649473 0.57100075 0.40294835]
 [0.34007074 0.94812017 0.07649863 0.51080079 0.79912304 0.37625205
  0.32837714 0.36312167 0.53772254 0.45732447]
 [0.05468311 0.10372834 0.22690334 0.2228935  0.84031653 0.99773118
  0.90561811 0.13830203 0.80295847 0.50352969]
 [0.47902913 0.09017466 0.45428977 0.21624232 0.96548607 0.39017118
  0.91376303 0.02297957 0.95869587 0.03067804]
 [0.34692272 0.04366339 0.93259912 0.07722943 0.61778638 0.72775206
  0.90251291 0.65293687 0.74493919 0.54066256]]

Subtract the mean of each row of the said matrix:

[[ 0.13921045  0.35660685 -0.33700383  0.41259746 -0.06202342 -0.15414296
  -0.17381849 -0.1674619   0.07704411 -0.09100828]
 [-0.13367039  0.47437905 -0.39724249  0.03705966  0.32538192 -0.09748907
  -0.14536399 -0.11061945  0.06398142 -0.01641665]
 [-0.42498332 -0.37593809 -0.25276309 -0.25677293  0.3606501   0.51806475
   0.42595168 -0.3413644   0.3

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [19]:
a1 = np.ones(10)
a2 = np.random.randint(0,len(a1),20)
a1 += np.bincount(a2, minlength=len(a1))
print(a1)
np.add.at(a1, a2, 1)
print(a1)

[3. 5. 2. 2. 6. 2. 3. 1. 4. 2.]
[ 5.  9.  3.  3. 11.  3.  5.  1.  7.  3.]


# 12.How to get the diagonal of a dot product?

In [20]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

array([1.81991711, 1.38788707, 1.68751834, 0.88320134, 1.11345564])

# 13.How to find the most frequent value in an array?

In [21]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


# 14.How to get the n largest values of an array

In [22]:
arr = np.arange(10000)
np.random.shuffle(arr)
n = 5
print (arr[np.argsort(arr)[-n:]])
print (arr[np.argpartition(-arr,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9996 9997 9995]


# 15.How to create a record array from a regular array?

In [23]:
arr1 = np.array([("Hello", 2.5, 3),
("World", 3.6, 2)])
arr2 = np.core.records.fromarrays(arr1.T,
names='col1, col2, col3',
formats = 'S8, f8, i8')
print(arr2)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
